name: 'Deploy to AWS S3'
description: 'Deploy a static Website via AWS S3'
inputs:
  bucket:
    description: 'Bucket'
    required: true
  bucket-region:
    description: 'Region of the bucket'
    required: false
    default: 'ca-central-1'
  dist-folder:
    description: 'The folder containing the code'
    required: true 
outputs:
  website-url:
    description: 'The URL of the deployed website'
runs:
  using: 'docker'
  image: 'Dockerfile'
